import { Provider } from 'jotai';
import type { Metadata } from 'next';
import SessionProvider from '../components/provider/SessionProvider';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <Provider>
      <SessionProvider>{children}</SessionProvider>
    </Provider>
  );
}
